org: malya
app: upside-app
service: upside-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  wiki:
    handler: handler.wiki_handler
    events:
      - http:
          path: /
          method: get

